require.config(
    {
        paths:{
            'jquery':"./jquery.min",
            'reg':'./lib/login',
            'md5':"./jquery.md5"
        },
        shim:{
            'md5':['jquery']
        }
    }
)
require(['jquery','reg'],function($,login){
   login.reg();
})